"""empty message

Revision ID: 17a4a79f7f75
Revises: fc1bc41cde5a
Create Date: 2025-01-27 20:12:50.306428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '17a4a79f7f75'
down_revision: Union[str, None] = 'fc1bc41cde5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faces',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('type', sa.Enum('natural', 'legal', name='typeface'), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('second_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('inn', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('ikps',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('agents',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('face_id', sa.Integer(), nullable=False),
                    sa.Column('ikp_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('project', 'active', 'ended', 'terminated', name='agent_statuses'),
                              nullable=False),
                    sa.Column('date_create', sa.DateTime(), nullable=False),
                    sa.Column('date_begin', sa.DateTime(), nullable=True),
                    sa.Column('date_end', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['face_id'], ['faces.id'], ),
                    sa.ForeignKeyConstraint(['ikp_id'], ['ikps.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('agent_agreements',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('agent_id', sa.Integer(), nullable=False),
                    sa.Column('lob_id', sa.Integer(), nullable=False),
                    sa.Column('rate', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_foreign_key(None, 'contract_risks', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract_risks', type='foreignkey')
    op.drop_table('agent_agreements')
    op.drop_table('agents')
    op.drop_table('ikps')
    op.drop_table('faces')
    # ### end Alembic commands ###
